<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<?php 
include_once "mycnn.php";
?>

<head>
<script src="https://code.jquery.com/jquery-latest.js"></script>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="receipt_delivery_files/filelist.xml">
<!--[if !mso]>
<style>
v\:* {behavior:url(#default#VML);}
o\:* {behavior:url(#default#VML);}
x\:* {behavior:url(#default#VML);}
.shape {behavior:url(#default#VML);}
</style>
<![endif]-->
<style id="receipt_delivery_17398_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.dong{
height: 88px;
    padding-bottom: 12px;
    padding-top: 3px;
    border: 0.5px solid black;
	text-align: center;
}
}	
.xl6617398
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6717398
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;
	margin-bottom:0px;
	}
.xl6817398
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:14.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6917398
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7017398
	{padding:0px;	
	mso-ignore:padding;
	color:#212529;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Tahoma, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;	
	white-space:normal;}
.xl7117398
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7217398
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:28.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7317398
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:22.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
-->
</style>
</head>

<body>
<div style="text-align:center"><h2>RECEIPT DELIVERY</h2></div>
<?php
if(isset($_REQUEST["dsChon"]))
{
	$dsChon=$_REQUEST["dsChon"];
	$mangChon=explode(",",$dsChon);
	for($i=1;$i<count($mangChon);$i++)
	{
		$trRoute="SELECT tr.TruckNo FROM tbl_route tr WHERE tr.ID_Route=".$mangChon[$i];
		$tbl=mysqli_query($cnn,$trRoute);
		$row=mysqli_fetch_assoc($tbl);
		$TruckNo=$row["TruckNo"];
		$ID_Route=$mangChon[$i];
		?>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="receipt_delivery_17398" align=center x:publishsource="Excel">
<div><hr style="width:30%"></div>
<table border=0 cellpadding=0 cellspacing=0 width=654 class=xl6617398
 style='border-collapse:collapse;width:491pt'>
 <col class=xl6617398 width=38 style='mso-width-source:userset;mso-width-alt:
 1389;width:29pt'>
 <col class=xl6617398 width=308 span=2 style='mso-width-source:userset;
 mso-width-alt:11264;width:231pt'>
 <tr height=84 style='mso-height-source:userset;height:63.0pt'>
  <td colspan=2 height=84 class=xl7317398 width=346 style='height:63.0pt;
  width:260pt'><?php echo $TruckNo;?></td>
  
    <td height=84 class=xl7217398 width=308 style='height:63.0pt;border-left:
    none;width:231pt'><?php 
	if($TruckNo!=""){
		echo "<img style='width:190px' src='barcode.php?codetype=code128&size=50&text=".$TruckNo."&print=true'/>";
	}
	?></td>
   </tr>
 <?php 
 	$strDetail="SELECT tu.Code,tu.PCS FROM tbl_unload tu WHERE tu.ID_Route=".$ID_Route;
	$tblDetail=mysqli_query($cnn,$strDetail);
	$stt=0;
	for($j=0;$j<mysqli_num_rows($tblDetail);$j++)
	{
		$row2=mysqli_fetch_assoc($tblDetail);
		$Code=$row2["Code"];
		$PCS=$row2["PCS"];
		$stt++;
	
 ?>
 <tr class="dong">
 <td class="dong"><?php echo $stt;?></td>
 <td class="dong">
 <?php 
  if($stt%2==0){
  	echo $Code."<br>";
	echo "<img style='width:190px' src='barcode.php?codetype=code128&size=40&text=".$Code."&print=true'/>";
	echo "<br>";
	echo $PCS ." PCS";
	 }?>
 </td>
 <td class="dong">
 <?php 
  if($stt%2!=0){
  	echo $Code."<br>";
	echo "<img style='width:190px' src='barcode.php?codetype=code128&size=40&text=".$Code."&print=true'/>";
	echo "<br>";
	echo $PCS ." PCS";
	 }?>
 </td>
 </tr>
 
 <?php }?>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=38 height="2" style='width:29pt'></td>
  <td width=308 style='width:231pt'></td>
  <td width=308 style='width:231pt'></td>
 </tr>
 <![endif]>
</table>

</div>
<?php 
	}
}
?>
<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
