<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<?php
header("Content-Type:   application/vnd.ms-excel; charset=utf-8");
header("Content-Disposition: attachment; filename=Receive report_".date('d/m/Y').".xls");	
?>
<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="rpt_received_files/filelist.xml">
<style id="rpt_received_11562_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl6311562
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:white;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:1.0pt solid silver;
	background:#3A8EBD;
	mso-pattern:black none;
	white-space:normal;}
.xl6411562
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6511562
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:1.0pt solid silver;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6611562
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border:1.0pt solid silver;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6711562
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6811562
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:1.0pt solid silver;
	background:lavender;
	mso-pattern:black none;
	white-space:normal;}
.xl6911562
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:right;
	vertical-align:bottom;
	border:1.0pt solid silver;
	background:lavender;
	mso-pattern:black none;
	white-space:normal;}
.xl7011562
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	background:lavender;
	mso-pattern:black none;
	white-space:nowrap;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="rpt_received_11562" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=772 class=xl6711562
 style='border-collapse:collapse;table-layout:fixed;width:580pt'>
 <col class=xl6411562 width=42 style='mso-width-source:userset;mso-width-alt:
 1194;width:32pt'>
 <col class=xl6711562 width=49 style='mso-width-source:userset;mso-width-alt:
 1393;width:37pt'>
 <col class=xl6711562 width=63 style='mso-width-source:userset;mso-width-alt:
 1792;width:47pt'>
 <col class=xl6711562 width=97 style='mso-width-source:userset;mso-width-alt:
 2759;width:73pt'>
 <col class=xl6711562 width=108 style='mso-width-source:userset;mso-width-alt:
 3072;width:81pt'>
 <col class=xl6711562 width=199 style='mso-width-source:userset;mso-width-alt:
 5660;width:149pt'>
 <col class=xl6711562 width=134 style='mso-width-source:userset;mso-width-alt:
 3811;width:101pt'>
 <col class=xl6711562 width=80 style='mso-width-source:userset;mso-width-alt:
 2275;width:60pt'>
 <tr class=xl6411562 height=35 style='mso-height-source:userset;height:26.25pt'>
  <td height=35 class=xl6311562 width=42 style='height:26.25pt;width:32pt'>&nbsp;</td>
  <td class=xl6311562 width=49 style='border-left:none;width:37pt'>Year</td>
  <td class=xl6311562 width=63 style='border-left:none;width:47pt'>Month</td>
  <td class=xl6311562 width=97 style='border-left:none;width:73pt'>Truck No.</td>
  <td class=xl6311562 width=108 style='border-left:none;width:81pt'>Code</td>
  <td class=xl6311562 width=199 style='border-left:none;width:149pt'>Product
  Name</td>
  <td class=xl6311562 width=134 style='border-left:none;width:101pt'>PCS INV</td>
  <td class=xl6311562 width=80 style='border-left:none;width:60pt'>PCS</td>
 </tr>
<?php
include_once "mycnn.php";
$id=$_REQUEST["id"]; //id=2019,8,29C-95313,3885A001
$id=str_replace("on/","",$id);
$mang=explode("/",$id);
 
$stt=0;
$tongPCS_Inv=0;
$tongPCS=0;
	
 for($x=0;$x<count($mang);$x++)
 {	
	list($nam,$thang,$bks,$code)=explode(",",$mang[$x]);
	$strTim="SELECT v.ProductName,v.PCS_INV,v.PCS_really FROM vwinboudsumary v WHERE v.Nam=".$nam." AND v.Thang=".$thang." AND v.Code='".$code."' AND v.TruckNo='".$bks."'";	
	$kq=mysqli_query($cnn,$strTim);
	$row=mysqli_fetch_assoc($kq);
	$stt+=1;
	$tongPCS_Inv+=$row["PCS_INV"];
	$tongPCS+=$row["PCS_really"];
 ?>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl6411562 style='height:16.5pt'><?php echo $stt;?></td>
  <td class=xl6511562 style='border-top:none'><?php echo $nam;?></td>
  <td class=xl6511562 style='border-top:none;border-left:none'><?php echo $thang;?></td>
  <td class=xl6511562 style='border-top:none;border-left:none'><?php echo $bks;?></td>
  <td class=xl6511562 style='border-top:none;border-left:none'><?php echo $code;?></td>
  <td class=xl6611562 style='border-top:none;border-left:none'><?php echo $row["ProductName"]?></td>
  <td class=xl6611562 align=right style='border-top:none;border-left:none'><?php echo $row["PCS_INV"]?></td>
  <td class=xl6611562 align=right style='border-top:none;border-left:none'><?php echo $row["PCS_really"]?></td>
 </tr>
<?php
 		
 	}
 ?>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl6811562 width=42 style='height:16.5pt;width:32pt'>&nbsp;</td>
  <td class=xl6811562 width=49 style='border-top:none;border-left:none;
  width:37pt'>&nbsp;</td>
  <td class=xl6811562 width=63 style='border-top:none;border-left:none;
  width:47pt'>&nbsp;</td>
  <td class=xl6811562 width=97 style='border-top:none;border-left:none;
  width:73pt'>&nbsp;</td>
  <td class=xl6811562 width=108 style='border-top:none;border-left:none;
  width:81pt'>&nbsp;</td>
  <td class=xl6811562 width=199 style='border-top:none;border-left:none;
  width:149pt'>&nbsp;</td>
  <td class=xl6911562 width=134 style='border-top:none;border-left:none;
  width:101pt'>Total: <?php echo number_format($tongPCS_Inv);?></td>
  <td class=xl6911562 width=80 style='border-top:none;border-left:none;
  width:60pt'>Total: <?php echo number_format($tongPCS,0);?></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=42 style='width:32pt'></td>
  <td width=49 style='width:37pt'></td>
  <td width=63 style='width:47pt'></td>
  <td width=97 style='width:73pt'></td>
  <td width=108 style='width:81pt'></td>
  <td width=199 style='width:149pt'></td>
  <td width=134 style='width:101pt'></td>
  <td width=80 style='width:60pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
